[env]
CHRONO_TZ_TIMEZONE_FILTER = "Europe/Berlin"

[profile.dev]
debug = "line-tables-only"
split-debuginfo = "unpacked"

[profile.dev.package."*"]
debug = false

[profile.debugging]
inherits = "dev"
debug = true
